---

apiVersion: v1
kind: Service
metadata:
  labels:
    service: llama-gpt-api
  name: llama-gpt-api
spec:
  ports:
    - name: api
      port: {{ .Values.api.service.port }}
      targetPort: {{ .Values.api.service.targetPort }}
  selector:
    service: llama-gpt-api
status:
  loadBalancer: {}

---

apiVersion: v1
kind: Service
metadata:
  labels:
    service: llama-gpt-ui
  name: llama-gpt-ui
spec:
  ports:
    - name: ui
      port: {{ .Values.ui.service.port }}
      targetPort: {{ .Values.ui.service.targetPort }}
  selector:
    service: llama-gpt-ui
  type: {{ .Values.ui.service.type }}
status:
  loadBalancer: {}

---
